FROM darthsim/imgproxy:latest

ENV IMGPROXY_NETWORK="tcp" \
    IMGPROXY_BIND=":8080" \
    IMGPROXY_LOG_LEVEL="info" \
    IMGPROXY_LOG_FORMAT="pretty" \
    IMGPROXY_BASE_URL="" \
    IMGPROXY_IGNORE_SSL_VERIFICATION=false \
    IMGPROXY_KEY="5b6085206efab2e4dfa7c7dae4ed27a64511ae21583f189c72f647e7d451c886" \
    IMGPROXY_SALT="72f1bb712c8a78a8f8f36b6a2d3f4799" \
    IMGPROXY_SIGNATURE_SIZE=32 \
    IMGPROXY_ALLOWED_SOURCES="https:" \
    IMGPROXY_ALLOW_PRIVATE_SOURCE_ADDRESSES=false \
    IMGPROXY_QUALITY=85 \
    IMGPROXY_FORMAT_QUALITY="jpeg=85,webp=75,avif=60" \
    IMGPROXY_PREFERRED_FORMATS="webp,avif,jpeg" \
    IMGPROXY_SKIP_PROCESSING_FORMATS="svg" \
    IMGPROXY_STRIP_METADATA=true \
    IMGPROXY_STRIP_COLOR_PROFILE=true \
    IMGPROXY_SANITIZE_SVG=true \
    IMGPROXY_AUTO_ROTATE=true \
    IMGPROXY_TTL=2592000 \
    IMGPROXY_CACHE_CONTROL_PASSTHROUGH=false

EXPOSE 8080

CMD ["imgproxy"]
